# Copyright (c) 2023 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Starting download of file
  ansible.builtin.debug:
    msg: "{{ download_artifact_url }}"

- name: Set source if not using mirror
  set_fact:
    source_url: "{{ download_artifact_url }}"

- name: Set source if downloading from mirror via the work directory (filename on mirror same as filename in work dir)
  when: ( download_artifact_mirror is defined ) and ( download_artifact_dest is not match('/usr/*') )
  set_fact:
    source_url: "{{ download_artifact_dest | regex_replace( download_artifact_work_directory, download_artifact_mirror ) }}"

- name: Set source if downloading from mirror directly to executable location
  when: ( download_artifact_mirror is defined ) and ( download_artifact_dest is match('/usr/*') )
  set_fact:
    source_url: "{{ download_artifact_mirror}}/{{ download_artifact_dest | split('/')[-1] }}-{{ download_artifact_mirror_version }}-{{ ansible_facts['system'] | lower }}-{{ download_artifact_goarch }}" # noqa: yaml[line-length]

- name: Display url when using mirror
  when: download_artifact_mirror is defined
  ansible.builtin.debug:
    msg: "Downloading from {{ source_url }}"

- name: Download item
  ansible.builtin.get_url:
    url: "{{ source_url }}"
    dest: "{{ download_artifact_dest }}"
    owner: "{{ download_artifact_owner | default(omit) }}"
    mode: "{{ download_artifact_mode | default(omit) }}"
    checksum: "{{ download_artifact_checksum | default(omit) }}"
    validate_certs: "{{ download_artifact_validate_certs | default(omit) }}"
    force_basic_auth: "{{ download_artifact_force_basic_auth | default(omit) }}"
    url_username: "{{ download_artifact_url_username | default(omit) }}"
    url_password: "{{ download_artifact_url_password | default(omit) }}"
  register: download_artifact_result
  until: download_artifact_result is succeeded
  retries: 4
  # NOTE(fitbeard): This task will avoid logging it's parameters to not leak
  #                 environment passwords in the log.
  no_log: "{{ download_artifact_no_log | bool }}"
  notify: "{{ download_artifact_notify }}"
  environment:
    http_proxy: "{{ download_artifact_http_proxy }}"
    https_proxy: "{{ download_artifact_https_proxy }}"
    no_proxy: "{{ download_artifact_no_proxy }}"

- name: Extract archive
  when: download_artifact_unarchive and not ansible_check_mode
  ansible.builtin.unarchive:
    src: "{{ download_artifact_dest }}"
    dest: "{{ download_artifact_unarchive_dest }}"
    owner: "{{ download_artifact_owner | default(omit) }}"
    mode: "{{ download_artifact_mode | default(omit) }}"
    remote_src: true
    include: "{{ download_artifact_unarchive_include | default(omit) }}"
    extra_opts: "{{ download_artifact_unarchive_extra_opts | default(omit) }}"
  notify: "{{ download_artifact_notify }}"
